# This is a basic workflow to help you get started with Actions

name: Serverless Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # NPM install
      - name: npm install
        run: sudo apt install npm
        shell: bash

      # Install serverless
      - name: install serverless
        run: sudo npm i -g serverless

      # Install Node dependencies
      - name: node dependencies
        run: npm install

      # Install Python and dependencies
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Deploy Serverless function
      - name: deploy app function
        run: sls deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          FQDN: ${{ secrets.FQDN }}
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
